# Generated by Django 2.0.3 on 2018-03-17 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=6)),
                ('phoneNumber', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'receiveinfo',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('receiveInformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.ReceiveInfo')),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
